a = float(input("Digite o primeiro número: "))
b = float(input("Digite o segundo número: "))
print("A soma dos dois números é", a + b,)
print("A multiplicação dos dois números é", a*b)
print("A subtração do primeiro número com o segundo resulta em", a-b)
print("A subtração do segundo número com o primeiro resulta em", b-a)
print("A divisão do primeiro número com o segundo resulta em", a/b)
print("A divisão do segundo número com o primeiro resulta em", b/a)
print("A exponenciação do primeiro pelo segundo resulta em", a**b)
print("A exponenciação do segundo pelo primeiro resulta em", b**a)
print("A divisão inteira do primeiro pelo segundo resulta em", a//b,"com resto", a%b)
print("A divisão inteira do segundo pelo primeiro resulta em", b//a,"com resto", b%a)