a = input("Digite qualquer coisa ")
alpha = a.isalpha()
dec = a.isdecimal()
asci = a.isascii()
alnum = a.isalnum()
digit = a.isdigit()
low = a.islower()
up = a.isupper()
ide = a.isidentifier()
tit = a.istitle()
num = a.isnumeric()
pri = a.isprintable()
print("True para quando houver, False para quando não houver.\n""O que foi digitado tem uma letra: {}".format(alpha))
print("O que foi digitado é um número decimal: {}".format(dec))
print("O que foi digitado é um caracter do ASCII: {}".format(asci))
print("O que foi digitado é um alfanúmerico: {}".format(alnum))
print("O que foi digitado é um dígito: {}".format(digit))
print("O que foi digitado está em minúsculo {}".format(low))
print("O que foi digitado está em maiúsculo: {}".format(up))
print("O que foi digitado é um identificador: {}".format(ide))
print("O que foi digitado é um título: {}".format(tit))
print("O que foi digitado é um número: {}".format(num))
print("O que foi digitado é imprimível: {}".format(dec))